version: '2'

services:  
  react:
    container_name: react
    build:
      context: react
      dockerfile: Dockerfile
    volumes:
      - './react:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      app_subnet:
        ipv4_address: 10.10.1.6

  stock:
    container_name: stock
    build:
      context: stock
      dockerfile: Dockerfile
    ports:
      - 3002:80
    networks:
      app_subnet:
        ipv4_address: 10.10.1.5

  ticketing:
    container_name: ticketing
    build:
      context: ticketing
      dockerfile: Dockerfile
    ports:
      - 3003:80
    networks:
      app_subnet:
        ipv4_address: 10.10.1.4        

  payments:
    container_name: payments
    build:
      context: payments
      dockerfile: Dockerfile
    ports:
      - 3004:80
    networks:
      app_subnet:
        ipv4_address: 10.10.1.3  

networks:
  app_subnet:
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1

