#Create App Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-payments
  namespace: egs3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-payments
  template:
    metadata:
      labels:
        app: app-payments
    spec:
      containers:
      - name: app-payments
        image: registry.deti:5000/ticketing/app-payments:2024
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: mariadb-payments-config 
        volumeMounts:
          - name: payments-secret
            mountPath: "/tmp/secrets"
            readOnly: true
      volumes:
        - name: payments-secret
          secret:
            secretName: payments-secret
      restartPolicy: Always

#Create Service
---
apiVersion: v1
kind: Service
metadata:
  name: app-payments
  namespace: egs3
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: app-payments